---
- name: reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  failed_when: false

- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  failed_when: false