---
- name: reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
    daemon_reload: yes

- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    daemon_reload: yes