---
- name: Create SSL virtual host config
  template:
    src: vhost-ssl.conf.j2
    dest: "/etc/nginx/sites-available/{{ item.server_name }}-ssl.conf"
    mode: '0644'
  register: ssl_config_result
  notify: reload nginx

- name: Enable SSL virtual host config
  file:
    src: "/etc/nginx/sites-available/{{ item.server_name }}-ssl.conf"
    dest: "/etc/nginx/sites-enabled/{{ item.server_name }}-ssl.conf"
    state: link
  register: ssl_symlink_result
  failed_when: >
    ssl_symlink_result.failed and 
    ('src file does not exist' not in ssl_symlink_result.msg)
  notify: reload nginx

- name: Create SSL redirect config if enabled
  template:
    src: vhost-redirect.conf.j2
    dest: "/etc/nginx/sites-available/{{ item.server_name }}.conf"
    mode: '0644'
  when: certbot.force_redirect | default(false)
  notify: reload nginx