---
- name: Ensure SSL directories exist for virtual host
  file:
    path: "/etc/apache2/sites-available/{{ item.server_name }}-ssl.conf"
    state: touch
    owner: root
    group: root
    mode: "0644"
  register: ssl_conf_file

- name: Check if SSL certificate exists for this domain
  stat:
    path: "/etc/letsencrypt/live/{{ item.server_name }}/fullchain.pem"
  register: cert_exists_for_domain

- name: Create SSL virtual host configuration
  template:
    src: vhost-ssl.conf.j2
    dest: "/etc/apache2/sites-available/{{ item.server_name }}-ssl.conf"
    owner: root
    group: root
    mode: "0644"
  when: cert_exists_for_domain.stat.exists | default(false)

- name: Configure HTTP site to redirect to HTTPS
  template:
    src: vhost-redirect.conf.j2
    dest: "/etc/apache2/sites-available/{{ item.server_name }}.conf"
    owner: root
    group: root
    mode: "0644"
  when: 
    - cert_exists_for_domain.stat.exists | default(false)
    - certbot.force_redirect | default(true)

- name: Validate Apache configuration
  command: apache2ctl configtest
  register: apache_config_test
  ignore_errors: yes
  changed_when: false
  when: cert_exists_for_domain.stat.exists | default(false)

- name: Enable SSL site if Apache config is valid
  command: a2ensite {{ item.server_name }}-ssl.conf
  args:
    creates: "/etc/apache2/sites-enabled/{{ item.server_name }}-ssl.conf"
  when: 
    - cert_exists_for_domain.stat.exists | default(false)
    - apache_config_test.rc == 0
  notify: restart apache