apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../shared
  - certificates/zachsexton-wildcard.yaml
  - certificates/argocd-cert.yaml
  - certificates/vigilo-dev-cert.yaml
  - certificates/petfoodfinder-app-cert.yaml
  - certificates/envoy-wildcard.yaml
  - certificates/personal-site-certificate.yaml
