apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vigilo-ingress
  namespace: web
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: vigilo.zachsexton.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vigilo
            port:
              number: 80
  - host: vigilo.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vigilo
            port:
              number: 80
