apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  # Production ingress files
  - ingress/argocd-ingress.yaml
  - ingress/ballroom-competition-web-ingress.yaml
  - ingress/ballroom-syllabi-ingress.yaml
  - ingress/personal-site-ingress.yaml
  - ingress/petfoodfinder-ingress.yaml
  - ingress/spotifybutler-ingress.yaml
  - ingress/vigilo-ingress.yaml
  - ingress/zot-ingress.yaml
