---
- name: Check if Apache is installed
  command: dpkg-query -W apache2
  register: apache_check
  failed_when: false
  changed_when: false

- name: Install Apache2 and required modules
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: present
    update_cache: true

# Use direct commands to manage Apache instead of relying on systemd/service
- name: Start Apache (direct command)
  command: /usr/sbin/apache2ctl start
  ignore_errors: true
  changed_when: false

- name: Wait for Apache to be up
  wait_for:
    path: /var/run/apache2/apache2.pid
    state: present
    timeout: 10
  ignore_errors: true

- name: Enable required Apache modules
  command: "a2enmod {{ item }}"
  args:
    creates: "/etc/apache2/mods-enabled/{{ item }}.load"
  loop:
    - rewrite
    - ssl
  register: modules_enabled
  changed_when: modules_enabled.changed

- name: Restart Apache after enabling modules
  command: /usr/sbin/apache2ctl restart
  when: modules_enabled.changed
  changed_when: false

- name: Ensure doc roots exist
  file:
    path: "{{ item.root }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"
  loop: "{{ sites }}"

- name: Create a default index.html for each site
  copy:
    dest: "{{ item.root }}/index.html"
    content: |
      <!DOCTYPE html>
      <html>
      <head>
          <title>Welcome to {{ item.server_name }}</title>
      </head>
      <body>
          <h1>Welcome to {{ item.server_name }}</h1>
          <p>If you see this page, Apache is successfully installed and working for this virtual host.</p>
      </body>
      </html>
    owner: www-data
    group: www-data
    mode: "0644"
  loop: "{{ sites }}"
  when: item.create_index | default(true)