---
- name: Deploy virtual host configs
  template:
    src: vhost.conf.j2
    dest: "/etc/apache2/sites-available/{{ item.server_name }}.conf"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ sites }}"
  notify: restart apache

- name: Disable default Apache site
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: restart apache

- name: Enable sites
  command: a2ensite {{ item.server_name }}.conf
  args:
    creates: "/etc/apache2/sites-enabled/{{ item.server_name }}.conf"
  loop: "{{ sites }}"
  notify: restart apache