---
- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Enable and start NGINX service
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes
    daemon_reload: yes


- name: Create directory for Let's Encrypt verification
  file:
    path: /var/www/letsencrypt/.well-known/acme-challenge
    state: directory
    mode: '0755'
    recurse: yes