---
- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: true

- name: Wait for systemd to recognize the new NGINX service
  ansible.builtin.command: systemctl daemon-reload
  changed_when: false

- name: Enable and start NGINX service (using command)
  ansible.builtin.command: systemctl start nginx
  changed_when: true
  ignore_errors: true

- name: Enable NGINX service on boot
  ansible.builtin.command: systemctl enable nginx
  changed_when: true
  ignore_errors: true

- name: Stop and disable Apache
  service:
    name: apache2
    state: stopped
    enabled: no
  ignore_errors: true

- name: Create directory for Let's Encrypt verification
  file:
    path: /var/www/letsencrypt/.well-known/acme-challenge
    state: directory
    mode: '0755'
    recurse: true