---
- name: Include cleanup tasks
  ansible.builtin.include_tasks: cleanup.yml

- name: Continue if NGINX is running
  ansible.builtin.command: systemctl is-active nginx
  register: nginx_running
  failed_when: false
  changed_when: false

- name: Include NGINX configuration tasks
  ansible.builtin.include_tasks: nginx_configuration.yml
  when: nginx_running.rc == 0

- name: Include vhosts configuration tasks
  ansible.builtin.include_tasks: vhosts.yml
  when: nginx_running.rc == 0