---
- name: Ensure NGINX base directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled

- name: Backup the default NGINX config
  ansible.builtin.command: cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak
  args:
    creates: /etc/nginx/nginx.conf.bak
  changed_when: true
  ignore_errors: yes

- name: Set NGINX default configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  notify: reload nginx

- name: Remove default NGINX site if it exists
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  ignore_errors: yes