apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: resend-api-key-ballroom-competition-web
  namespace: web
spec:
  itemPath: "vaults/Kubernetes/items/resend-api-key-ballroom-competition-web"
