#!/usr/bin/env bash
# Bring staging up or down with one command.
#
#   ./scripts/staging.sh up        # IP -> manifests -> server -> k3s -> Argo CD
#   ./scripts/staging.sh down      # destroy the server, keep the address and DNS
#   ./scripts/staging.sh status    # what exists right now
#   ./scripts/staging.sh verify    # every configured URL, with real TLS validation
#   ./scripts/staging.sh kubeconfig
#   ./scripts/staging.sh ssh       # shell on the staging box
#   ./scripts/staging.sh relocate  # move to another Hetzner location (new address)
#   ./scripts/staging.sh nuke      # release the address too (rarely what you want)
#
# `down` deliberately keeps the primary IP. The server is ~EUR 8/month and an
# unassigned primary IPv4 is ~EUR 0.60, so keeping it saves over 90% while
# leaving the address -- and therefore the IP hardcoded in
# k8s/argocd/staging/traefik.yaml and the MetalLB pool -- valid across cycles.
# That is what makes `up` a single command on every cycle after the first.
#
# The DNS records are torn down with the server and recreated by `up`. They point
# at the retained address, so they come back identical. (They cannot be kept: the
# module derives the record content from a conditional that names both the
# primary IP and the server, and Terraform builds its dependency graph from every
# reference in an expression rather than from the branch that actually evaluates,
# so the records depend on the server either way.)
#
# The only values you must supply are the Hetzner and Cloudflare credentials.
# The SSH keypair is generated by Terraform; the k3s token and the Argo CD admin
# password are generated here on first run and reused thereafter.
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
TF_DIR="$REPO/terraform/envs/staging"
TFVARS="$TF_DIR/terraform.tfvars"
IP_ADDR='module.env.hcloud_primary_ip.protected[0]'
SERVER='module.env.hcloud_server.this'

red()   { printf '\033[0;31m%s\033[0m\n' "$*" >&2; }
green() { printf '\033[0;32m%s\033[0m\n' "$*"; }
warn()  { printf '\033[1;33m%s\033[0m\n' "$*"; }
step()  { printf '\033[1;36m==> %s\033[0m\n' "$*"; }
die()   { red "error: $*"; exit 1; }

tf() { terraform -chdir="$TF_DIR" "$@"; }

# Only things that must come from outside. Everything else is generated.
REQUIRED_VARS=(
  hcloud_token
  cloudflare_api_token
  cloudflare_zone_id_zachsexton
  cloudflare_zone_id_petfoodfinder
  cloudflare_zone_id_vigilo
)

has_value() { grep -qE "^$1[[:space:]]*=[[:space:]]*(\"[^\"]+\"|<<)" "$TFVARS"; }

set_var() { # name value
  TFVARS="$TFVARS" VNAME="$1" VVALUE="$2" python3 - <<'PY'
import json, os, re
p, n, v = os.environ["TFVARS"], os.environ["VNAME"], os.environ["VVALUE"]
s = open(p).read()
line = "%s = %s" % (n, json.dumps(v))
if re.search(r"^%s\s*=" % re.escape(n), s, re.M):
    s = re.sub(r"^%s\s*=.*$" % re.escape(n), line, s, count=1, flags=re.M)
else:
    s = s.rstrip("\n") + "\n" + line + "\n"
open(p, "w").write(s)
PY
}

# Generated once and reused, so spin-up/down cycles keep the same cluster token
# and the same Argo CD password.
ensure_generated_secrets() {
  if ! has_value k3s_token; then
    step "generating k3s_token"
    set_var k3s_token "$(openssl rand -hex 32)"
  fi

  if ! has_value argocd_admin_password_bcrypt; then
    command -v htpasswd >/dev/null \
      || die "htpasswd not found (apt install apache2-utils); needed to hash the Argo CD password"
    local pw hash
    pw=$(openssl rand -base64 24 | tr -dc 'A-Za-z0-9' | cut -c1-20)
    hash=$(htpasswd -nbBC 10 admin "$pw" | cut -d: -f2)
    set_var argocd_admin_password_bcrypt "$hash"
    step "generated an Argo CD admin password"
    warn "Argo CD login:  admin / $pw"
    warn "Shown once. Only recoverable by regenerating the hash."
  fi
}

preflight() {
  command -v terraform >/dev/null || die "terraform not on PATH"
  [ -f "$TFVARS" ] || die "missing $TFVARS -- copy terraform.tfvars.example and fill it in"

  local missing=()
  for v in "${REQUIRED_VARS[@]}"; do
    has_value "$v" || missing+=("$v")
  done
  if [ "${#missing[@]}" -gt 0 ]; then
    red "these must be set in $TFVARS:"
    printf '  %s\n' "${missing[@]}" >&2
    exit 1
  fi

  ensure_generated_secrets

  for v in onepassword_connect_token onepassword_credentials_json; do
    has_value "$v" || {
      warn "$v is empty: the bootstrap will skip 1Password, leaving"
      warn "  onepassword-operator Degraded and every OnePasswordItem-backed"
      warn "  secret missing (cloudflare-api-token, firebase, ...)."
      break
    }
  done
}

is_ipv4() { [[ "$1" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; }

# Outputs are not evaluated during a -target apply, and `terraform output` prints
# a "No outputs found" warning on stdout rather than failing, so the value is
# always validated and falls back to reading the address straight out of state.
current_ip() {
  local ip
  ip=$(tf output -raw ipv4_address 2>/dev/null || true)
  if ! is_ipv4 "$ip"; then
    ip=$(tf state show "$IP_ADDR" 2>/dev/null \
         | grep -oP '^\s*ip_address\s*=\s*"\K[0-9.]+' || true)
  fi
  is_ipv4 "$ip" && printf '%s' "$ip" || true
}

manifest_ip() {
  grep -oP 'loadBalancerIP:\s*\K[0-9.]+' "$REPO/k8s/argocd/staging/traefik.yaml" 2>/dev/null || true
}

# Argo CD tracks the repo default branch, so manifest changes only reach the
# cluster once they are on master and pushed.
sync_manifests() {
  local ip="$1"
  [ -n "$ip" ] || die "no IP to write into the manifests"

  if [ "$(manifest_ip)" = "$ip" ]; then
    green "manifests already point at $ip"
    return 0
  fi

  step "pointing staging manifests at $ip"
  "$REPO/scripts/setup/set-env-ip.sh" staging "$ip"

  local branch
  branch=$(git -C "$REPO" branch --show-current)
  git -C "$REPO" add k8s
  git -C "$REPO" commit -q -m "Point staging manifests at $ip" || true

  if [ "$branch" != "master" ]; then
    warn "on branch '$branch', not master. Argo CD tracks master, so it will not"
    warn "see this until the branch is merged: the cluster comes up but every"
    warn "staging ingress stays down until then."
    return 0
  fi

  git -C "$REPO" push -q || {
    warn "could not push. Argo CD reads from GitHub, so staging ingress stays"
    warn "down until these manifests are pushed."
  }
}

cmd_up() {
  preflight
  step "terraform init"
  tf init -input=false >/dev/null

  step "allocating the primary IP (kept across spin-downs)"
  tf apply -input=false -auto-approve -target="$IP_ADDR" >/dev/null
  local ip
  ip=$(current_ip)
  [ -n "$ip" ] || die "could not read the primary IP after allocating it"
  green "staging address: $ip"

  # Before the server exists, so Argo CD converges on the right IP at its first
  # sync instead of syncing a stale one and having to self-heal.
  sync_manifests "$ip"

  step "building the server and running the bootstrap (k3s, Argo CD, root app)"
  tf apply -input=false -auto-approve

  cmd_kubeconfig >/dev/null 2>&1 || true

  echo
  green "staging is up at $ip"
  echo
  cmd_status
  echo
  step "waiting for Argo CD to sync, then checking every configured URL"
  # Argo CD needs a couple of minutes to work through sync waves -1..2 before any
  # ingress can serve, so give it that before declaring anything broken.
  local i=0
  until [ $i -ge 18 ]; do
    kubectl --kubeconfig "$REPO/kubeconfig-staging.yaml" -n argocd get applications \
      -o json 2>/dev/null \
      | jq -e '[.items[] | select(.status.sync.status != "Synced")] | length == 0' >/dev/null 2>&1 && break
    i=$((i+1)); sleep 10
  done
  echo
  cmd_verify || true
}

cmd_down() {
  [ -d "$TF_DIR/.terraform" ] || tf init -input=false >/dev/null
  local ip
  ip=$(current_ip)

  step "destroying the staging server, keeping the address $ip"
  # Targeted rather than a full destroy: the primary IP carries prevent_destroy,
  # which a plain `terraform destroy` would fail on. The DNS records go too --
  # they depend on the server through the module's conditional -- and `up`
  # recreates them against the same retained address.
  tf destroy -input=false -auto-approve -target="$SERVER"

  echo
  green "staging is down. Address $ip retained, so 'up' stays a single command"
  green "and the k8s manifests that hardcode it stay valid."
  warn "DNS records were removed with the server; 'up' recreates them at $ip."
  warn "An unassigned primary IPv4 still bills at roughly EUR 0.60/month."
}

cmd_nuke() {
  warn "This releases the staging address as well as the server."
  warn "The IP is hardcoded in k8s/argocd/staging/traefik.yaml and the MetalLB"
  warn "pool; the next 'up' gets a different address and rewrites both."
  read -r -p "Type 'nuke' to continue: " reply
  [ "$reply" = "nuke" ] || die "aborted"

  tf destroy -input=false -auto-approve -target="$SERVER"
  release_address
}

hcloud_token() { grep -oP '^hcloud_token\s*=\s*"\K[^"]+' "$TFVARS"; }

state_ip_location() {
  tf state show "$IP_ADDR" 2>/dev/null | grep -oP '^\s*location\s*=\s*"\K[^"]+' || true
}

# Drop the address from state and release it through the API.
#
# prevent_destroy is a literal in the shared module and cannot be lifted for one
# environment from a script, so terraform can never be the thing that deletes
# this resource. Removing it from state first means a failed API call leaves an
# orphan that still bills, so the deletion is verified by reading the address
# back rather than trusting curl's exit code.
release_address() {
  local id ip
  id=$(tf state show "$IP_ADDR" 2>/dev/null | grep -oP '^\s*id\s*=\s*"\K[0-9]+' || true)
  ip=$(current_ip)
  [ -n "$id" ] || die "could not determine the primary IP id"

  tf state rm "$IP_ADDR" >/dev/null
  local token; token=$(hcloud_token)
  curl -sS -X DELETE -H "Authorization: Bearer $token" \
    "https://api.hetzner.cloud/v1/primary_ips/$id" >/dev/null || true

  # Read back. A 404 here is the success case.
  local code
  code=$(curl -sS -o /dev/null -w '%{http_code}' -H "Authorization: Bearer $token" \
    "https://api.hetzner.cloud/v1/primary_ips/$id")
  if [ "$code" = "404" ]; then
    green "released $ip (id $id) and removed it from state"
  else
    red "primary IP $id still exists at Hetzner (HTTP $code) but is no longer in"
    red "state, so terraform will not clean it up. Delete it by hand:"
    red "  ./scripts/setup/hcloud-primary-ip.sh list"
    exit 1
  fi
}

# ---------------------------------------------------------------------------
# Moving staging to another Hetzner location.
#
# Three things here are pinned to a region and none of them can be moved in
# place:
#
#   primary IP  Hetzner allocates it in a location and offers no API to move it.
#               A region change therefore means a NEW ADDRESS, which is why this
#               cannot be folded into `up`: the two manifests that hardcode the
#               address have to be rewritten and pushed before Argo CD syncs.
#   subnet      network_zone is ForceNew. (The network itself is global.)
#   server      location is ForceNew.
#
# So relocating is a release-and-rebuild, not an edit. That is only cheap
# because staging is already built to be destroyed -- `up` is a single command
# and nothing on the box is stateful that git does not already describe.
#
# Edit location/server_type/network_zone in terraform/envs/staging/main.tf
# first, then run this. `relocate check` reports without changing anything.

zone_for_location() {
  case "$1" in
    fsn1|nbg1|hel1) echo eu-central ;;
    ash)            echo us-east ;;
    hil)            echo us-west ;;
    sin)            echo ap-southeast ;;
    *)              echo "" ;;
  esac
}

tf_setting() { # key -- as literally written in the staging module block
  grep -oP "^\s*$1\s*=\s*\"\K[^\"]+" "$TF_DIR/main.tf" | head -1
}

# Not every server type exists in every location -- cx23 is EU-only, and asking
# for one in ash fails at apply time after the address has already been
# released. Ask Hetzner instead of assuming.
type_in_location() { # server_type location
  HTOKEN="$(hcloud_token)" ST="$1" LOC="$2" python3 - <<'PY'
import json, os, sys, urllib.request
req = urllib.request.Request("https://api.hetzner.cloud/v1/server_types?per_page=100",
                             headers={"Authorization": "Bearer " + os.environ["HTOKEN"]})
want, loc = os.environ["ST"], os.environ["LOC"]
for st in json.load(urllib.request.urlopen(req))["server_types"]:
    if st["name"] != want:
        continue
    prices = {p["location"]: float(p["price_monthly"]["gross"]) for p in st["prices"]}
    if loc in prices:
        print("ok|%d cores / %gGB / %dGB %s|$%.2f/mo"
              % (st["cores"], st["memory"], st["disk"], st["cpu_type"], prices[loc]))
    else:
        print("unavailable|%s is not offered in %s|only: %s"
              % (want, loc, ", ".join(sorted(prices))))
    sys.exit(0)
print("nosuchtype|no server type named %s|" % want)
PY
}

cmd_relocate() {
  local check=""
  [ "${1:-}" = "check" ] && check=1
  [ -d "$TF_DIR/.terraform" ] || tf init -input=false >/dev/null

  local want_loc want_type want_zone have_loc
  want_loc=$(tf_setting location)
  want_type=$(tf_setting server_type)
  want_zone=$(tf_setting network_zone)
  have_loc=$(state_ip_location)

  [ -n "$want_loc" ]  || die "no location set in $TF_DIR/main.tf"
  [ -n "$want_type" ] || die "no server_type set in $TF_DIR/main.tf"

  # A location/network_zone mismatch is accepted by terraform and then fails
  # deep in the apply, after the address is gone.
  local expect_zone; expect_zone=$(zone_for_location "$want_loc")
  [ -n "$expect_zone" ] || die "unknown location '$want_loc'"
  if [ -n "$want_zone" ] && [ "$want_zone" != "$expect_zone" ]; then
    die "network_zone is '$want_zone' but $want_loc is in '$expect_zone' -- fix $TF_DIR/main.tf"
  fi
  if [ -z "$want_zone" ]; then
    die "set network_zone = \"$expect_zone\" in $TF_DIR/main.tf (it defaults to us-east)"
  fi

  local info status detail price
  info=$(type_in_location "$want_type" "$want_loc")
  IFS='|' read -r status detail price <<<"$info"
  [ "$status" = "ok" ] || die "$detail${price:+ ($price)}"

  step "target"
  printf '  location     %s (network zone %s)\n' "$want_loc" "$want_zone"
  printf '  server type  %-8s %s  %s\n' "$want_type" "$detail" "$price"

  local have_ip; have_ip=$(current_ip)
  step "current"
  printf '  address      %s in %s\n' "${have_ip:-<none>}" "${have_loc:-<none>}"
  if tf state list 2>/dev/null | grep -qx "$SERVER"; then
    printf '  server       present\n'
  else
    printf '  server       DOWN\n'
  fi

  if [ "$have_loc" = "$want_loc" ]; then
    echo
    green "already in $want_loc -- nothing to relocate. Run: $0 up"
    return 0
  fi
  # After a `nuke` there is no address to release, so there is nothing to
  # relocate either -- `up` allocates straight into the configured location.
  if [ -z "$have_loc" ]; then
    echo
    green "no address allocated, so nothing is pinned to the old region."
    green "Run: $0 up   (it will allocate in $want_loc)"
    return 0
  fi

  echo
  step "what this does"
  echo "  1. destroy the server, if one is up"
  echo "  2. release ${have_ip:-the current address} -- a primary IP cannot change region"
  echo "  3. allocate a new address in $want_loc"
  echo "  4. rewrite the address in k8s/argocd/staging/traefik.yaml and the"
  echo "     MetalLB pool, commit and push (Argo CD reads these from master)"
  echo "  5. build the $want_type and run the bootstrap"
  echo
  warn "  every staging DNS record moves to the new address with it."

  [ -z "$check" ] || { echo; green "check only -- nothing changed"; return 0; }

  echo
  read -r -p "Type 'relocate' to continue: " reply
  [ "$reply" = "relocate" ] || die "aborted"

  if tf state list 2>/dev/null | grep -qx "$SERVER"; then
    step "destroying the server in $have_loc"
    tf destroy -input=false -auto-approve -target="$SERVER"
  fi

  step "releasing the $have_loc address"
  release_address

  cmd_up
}

cmd_status() {
  [ -d "$TF_DIR/.terraform" ] || tf init -input=false >/dev/null
  local ip
  ip=$(current_ip)
  printf 'address (terraform) : %s\n' "${ip:-<none>}"
  printf 'address (manifests) : %s\n' "$(manifest_ip)"
  if [ -n "$ip" ] && [ "$(manifest_ip)" != "$ip" ]; then
    warn "MISMATCH -- Traefik's LoadBalancer will stay pending. Run: $0 up"
  fi

  if tf state list 2>/dev/null | grep -qx "$SERVER"; then
    printf 'server              : present\n'
    if [ -n "$ip" ]; then
      if timeout 5 bash -c "echo > /dev/tcp/$ip/6443" 2>/dev/null; then
        printf 'k3s api (6443)      : open\n'
      else
        printf 'k3s api (6443)      : closed\n'
      fi
      if timeout 5 bash -c "echo > /dev/tcp/$ip/443" 2>/dev/null; then
        printf 'ingress (443)       : open\n'
      else
        printf 'ingress (443)       : closed (Traefik may still be syncing)\n'
      fi
    fi
  else
    printf 'server              : DOWN (spun down)\n'
  fi
}

cmd_verify() {
  local ip; ip=$(current_ip)
  [ -n "$ip" ] || die "staging has no address; run: $0 up"
  "$REPO/scripts/lib/verify-env.sh" "$ip" "$REPO/kubeconfig-staging.yaml"
}

keyfile() {
  local f="$TF_DIR/.ssh_key"
  tf output -raw ssh_private_key > "$f"
  chmod 600 "$f"
  printf '%s' "$f"
}

# Every spin-up rebuilds the host onto the same address with a fresh host key, so
# the stale known_hosts entry has to go or SSH refuses to connect.
ssh_to() { # ip [args...]
  local ip="$1"; shift
  local key; key=$(keyfile)
  ssh-keygen -R "$ip" >/dev/null 2>&1 || true
  ssh -i "$key" \
      -o StrictHostKeyChecking=accept-new \
      -o IdentitiesOnly=yes \
      -o ConnectTimeout=15 \
      "root@$ip" "$@"
}

cmd_kubeconfig() {
  local ip
  ip=$(current_ip)
  [ -n "$ip" ] || die "staging has no address; run: $0 up"
  local out="$REPO/kubeconfig-staging.yaml" tmp
  tmp=$(mktemp)
  ssh_to "$ip" cat /etc/rancher/k3s/k3s.yaml > "$tmp" || die "could not read the kubeconfig over SSH"
  # Do not overwrite a good kubeconfig with an error page.
  grep -q '^apiVersion:' "$tmp" || { rm -f "$tmp"; die "what came back is not a kubeconfig"; }
  sed "s/127.0.0.1/$ip/" "$tmp" > "$out"
  rm -f "$tmp"
  chmod 600 "$out"
  green "wrote $out"
  echo "export KUBECONFIG=$out"
}

cmd_ssh() {
  local ip
  ip=$(current_ip)
  [ -n "$ip" ] || die "staging has no address; run: $0 up"
  ssh_to "$ip" "$@"
}

case "${1:-}" in
  up)         cmd_up ;;
  down)       cmd_down ;;
  nuke)       cmd_nuke ;;
  relocate)   shift; cmd_relocate "$@" ;;
  status)     cmd_status ;;
  verify)     cmd_verify ;;
  kubeconfig) cmd_kubeconfig ;;
  ssh)        shift; cmd_ssh "$@" ;;
  *) echo "usage: $0 {up|down|relocate|status|verify|kubeconfig|ssh|nuke}" >&2; exit 1 ;;
esac
