#!/usr/bin/env bash
# Bring staging up or down with one command.
#
#   ./scripts/staging.sh up        # IP -> manifests -> server -> k3s -> Argo CD
#   ./scripts/staging.sh down      # destroy the server, keep the address and DNS
#   ./scripts/staging.sh status    # what exists right now
#   ./scripts/staging.sh kubeconfig
#   ./scripts/staging.sh ssh       # shell on the staging box
#   ./scripts/staging.sh nuke      # release the address too (rarely what you want)
#
# `down` deliberately keeps the primary IP. The server is ~EUR 8/month and an
# unassigned primary IPv4 is ~EUR 0.60, so keeping it saves over 90% while
# leaving the address -- and therefore the DNS records and the IP hardcoded in
# k8s/argocd/staging/traefik.yaml and the MetalLB pool -- valid across cycles.
# That is what makes `up` a single command on every cycle after the first.
#
# The only values you must supply are the Hetzner and Cloudflare credentials.
# The SSH keypair is generated by Terraform; the k3s token and the Argo CD admin
# password are generated here on first run and reused thereafter.
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
TF_DIR="$REPO/terraform/envs/staging"
TFVARS="$TF_DIR/terraform.tfvars"
IP_ADDR='module.env.hcloud_primary_ip.protected[0]'
SERVER='module.env.hcloud_server.this'

red()   { printf '\033[0;31m%s\033[0m\n' "$*" >&2; }
green() { printf '\033[0;32m%s\033[0m\n' "$*"; }
warn()  { printf '\033[1;33m%s\033[0m\n' "$*"; }
step()  { printf '\033[1;36m==> %s\033[0m\n' "$*"; }
die()   { red "error: $*"; exit 1; }

tf() { terraform -chdir="$TF_DIR" "$@"; }

# Only things that must come from outside. Everything else is generated.
REQUIRED_VARS=(
  hcloud_token
  cloudflare_api_token
  cloudflare_zone_id_zachsexton
  cloudflare_zone_id_petfoodfinder
  cloudflare_zone_id_vigilo
)

has_value() { grep -qE "^$1[[:space:]]*=[[:space:]]*(\"[^\"]+\"|<<)" "$TFVARS"; }

set_var() { # name value
  TFVARS="$TFVARS" VNAME="$1" VVALUE="$2" python3 - <<'PY'
import json, os, re
p, n, v = os.environ["TFVARS"], os.environ["VNAME"], os.environ["VVALUE"]
s = open(p).read()
line = "%s = %s" % (n, json.dumps(v))
if re.search(r"^%s\s*=" % re.escape(n), s, re.M):
    s = re.sub(r"^%s\s*=.*$" % re.escape(n), line, s, count=1, flags=re.M)
else:
    s = s.rstrip("\n") + "\n" + line + "\n"
open(p, "w").write(s)
PY
}

# Generated once and reused, so spin-up/down cycles keep the same cluster token
# and the same Argo CD password.
ensure_generated_secrets() {
  if ! has_value k3s_token; then
    step "generating k3s_token"
    set_var k3s_token "$(openssl rand -hex 32)"
  fi

  if ! has_value argocd_admin_password_bcrypt; then
    command -v htpasswd >/dev/null \
      || die "htpasswd not found (apt install apache2-utils); needed to hash the Argo CD password"
    local pw hash
    pw=$(openssl rand -base64 24 | tr -dc 'A-Za-z0-9' | cut -c1-20)
    hash=$(htpasswd -nbBC 10 admin "$pw" | cut -d: -f2)
    set_var argocd_admin_password_bcrypt "$hash"
    step "generated an Argo CD admin password"
    warn "Argo CD login:  admin / $pw"
    warn "Shown once. Only recoverable by regenerating the hash."
  fi
}

preflight() {
  command -v terraform >/dev/null || die "terraform not on PATH"
  [ -f "$TFVARS" ] || die "missing $TFVARS -- copy terraform.tfvars.example and fill it in"

  local missing=()
  for v in "${REQUIRED_VARS[@]}"; do
    has_value "$v" || missing+=("$v")
  done
  if [ "${#missing[@]}" -gt 0 ]; then
    red "these must be set in $TFVARS:"
    printf '  %s\n' "${missing[@]}" >&2
    exit 1
  fi

  ensure_generated_secrets

  for v in onepassword_connect_token onepassword_credentials_json; do
    has_value "$v" || {
      warn "$v is empty: the bootstrap will skip 1Password, leaving"
      warn "  onepassword-operator Degraded and every OnePasswordItem-backed"
      warn "  secret missing (cloudflare-api-token, zot-auth, ...)."
      break
    }
  done
}

current_ip() { tf output -raw ipv4_address 2>/dev/null || true; }

manifest_ip() {
  grep -oP 'loadBalancerIP:\s*\K[0-9.]+' "$REPO/k8s/argocd/staging/traefik.yaml" 2>/dev/null || true
}

# Argo CD tracks the repo default branch, so manifest changes only reach the
# cluster once they are on master and pushed.
sync_manifests() {
  local ip="$1"
  [ -n "$ip" ] || die "no IP to write into the manifests"

  if [ "$(manifest_ip)" = "$ip" ]; then
    green "manifests already point at $ip"
    return 0
  fi

  step "pointing staging manifests at $ip"
  "$REPO/scripts/set-env-ip.sh" staging "$ip"

  local branch
  branch=$(git -C "$REPO" branch --show-current)
  git -C "$REPO" add k8s
  git -C "$REPO" commit -q -m "Point staging manifests at $ip" || true

  if [ "$branch" != "master" ]; then
    warn "on branch '$branch', not master. Argo CD tracks master, so it will not"
    warn "see this until the branch is merged: the cluster comes up but every"
    warn "staging ingress stays down until then."
    return 0
  fi

  git -C "$REPO" push -q || {
    warn "could not push. Argo CD reads from GitHub, so staging ingress stays"
    warn "down until these manifests are pushed."
  }
}

cmd_up() {
  preflight
  step "terraform init"
  tf init -input=false >/dev/null

  step "allocating the primary IP (kept across spin-downs)"
  tf apply -input=false -auto-approve -target="$IP_ADDR" >/dev/null
  local ip
  ip=$(current_ip)
  [ -n "$ip" ] || die "could not read the primary IP after allocating it"
  green "staging address: $ip"

  # Before the server exists, so Argo CD converges on the right IP at its first
  # sync instead of syncing a stale one and having to self-heal.
  sync_manifests "$ip"

  step "building the server and running the bootstrap (k3s, Argo CD, root app)"
  tf apply -input=false -auto-approve

  echo
  green "staging is up at $ip"
  echo
  cmd_status
}

cmd_down() {
  [ -d "$TF_DIR/.terraform" ] || tf init -input=false >/dev/null
  local ip
  ip=$(current_ip)

  step "destroying the staging server, keeping $ip and the DNS records"
  # Targeted: the primary IP carries prevent_destroy, and the DNS records depend
  # on the address rather than the server, so both survive. A plain
  # `terraform destroy` would fail on that prevent_destroy.
  tf destroy -input=false -auto-approve -target="$SERVER"

  echo
  green "staging is down. Address $ip retained, so 'up' stays a single command."
  warn "An unassigned primary IPv4 still bills at roughly EUR 0.60/month."
}

cmd_nuke() {
  warn "This releases the staging address as well as the server."
  warn "The IP is hardcoded in k8s/argocd/staging/traefik.yaml and the MetalLB"
  warn "pool; the next 'up' gets a different address and rewrites both."
  read -r -p "Type 'nuke' to continue: " reply
  [ "$reply" = "nuke" ] || die "aborted"

  tf destroy -input=false -auto-approve -target="$SERVER"

  local id
  id=$(tf state show "$IP_ADDR" 2>/dev/null | grep -oP '^\s*id\s*=\s*"\K[0-9]+' || true)
  [ -n "$id" ] || die "could not determine the primary IP id"
  # prevent_destroy cannot be lifted from a script, so the address is dropped
  # from state and released through the API.
  tf state rm "$IP_ADDR" >/dev/null
  local token
  token=$(grep -oP '^hcloud_token\s*=\s*"\K[^"]+' "$TFVARS")
  curl -sSf -X DELETE -H "Authorization: Bearer $token" \
    "https://api.hetzner.cloud/v1/primary_ips/$id" >/dev/null
  green "address released and removed from state"
}

cmd_status() {
  [ -d "$TF_DIR/.terraform" ] || tf init -input=false >/dev/null
  local ip
  ip=$(current_ip)
  printf 'address (terraform) : %s\n' "${ip:-<none>}"
  printf 'address (manifests) : %s\n' "$(manifest_ip)"
  if [ -n "$ip" ] && [ "$(manifest_ip)" != "$ip" ]; then
    warn "MISMATCH -- Traefik's LoadBalancer will stay pending. Run: $0 up"
  fi

  if tf state list 2>/dev/null | grep -qx "$SERVER"; then
    printf 'server              : present\n'
    if [ -n "$ip" ]; then
      if timeout 5 bash -c "echo > /dev/tcp/$ip/6443" 2>/dev/null; then
        printf 'k3s api (6443)      : open\n'
      else
        printf 'k3s api (6443)      : closed\n'
      fi
      if timeout 5 bash -c "echo > /dev/tcp/$ip/443" 2>/dev/null; then
        printf 'ingress (443)       : open\n'
      else
        printf 'ingress (443)       : closed (Traefik may still be syncing)\n'
      fi
    fi
  else
    printf 'server              : DOWN (spun down)\n'
  fi
}

keyfile() {
  local f="$TF_DIR/.ssh_key"
  tf output -raw ssh_private_key > "$f"
  chmod 600 "$f"
  printf '%s' "$f"
}

cmd_kubeconfig() {
  local ip
  ip=$(current_ip)
  [ -n "$ip" ] || die "staging has no address; run: $0 up"
  local out="$REPO/kubeconfig-staging.yaml" key
  key=$(keyfile)
  ssh -i "$key" -o StrictHostKeyChecking=accept-new "root@$ip" \
    cat /etc/rancher/k3s/k3s.yaml | sed "s/127.0.0.1/$ip/" > "$out"
  chmod 600 "$out"
  green "wrote $out"
  echo "export KUBECONFIG=$out"
}

cmd_ssh() {
  local ip key
  ip=$(current_ip)
  [ -n "$ip" ] || die "staging has no address; run: $0 up"
  key=$(keyfile)
  exec ssh -i "$key" -o StrictHostKeyChecking=accept-new "root@$ip" "$@"
}

case "${1:-}" in
  up)         cmd_up ;;
  down)       cmd_down ;;
  nuke)       cmd_nuke ;;
  status)     cmd_status ;;
  kubeconfig) cmd_kubeconfig ;;
  ssh)        shift; cmd_ssh "$@" ;;
  *) echo "usage: $0 {up|down|status|kubeconfig|ssh|nuke}" >&2; exit 1 ;;
esac
