# One list entry per virtual host you want on this server.
sites:
  - server_name: zachsexton.com
    root: /var/www/zachsexton.com/html
    aliases:
      - path: /font-helper
        directory: /var/www/zachsexton.com/font-helper
      - path: /music-butler
        directory: /var/www/zachsexton.com/music-butler
    certbot_email: webmaster@zachsexton.com

  - server_name: petfoodfinder.app
    root: /var/www/petfoodfinder.app/html
    certbot_email: webmaster@petfoodfinder.app

  - server_name: vigilo.dev
    root: /var/www/vigilo.dev/html
    certbot_email: webmaster@vigilo.dev

# Certbot configuration
certbot:
  use_staging: false  # Set to true for testing
  webroot_path: /var/www/html  # Default webroot path
  standalone: false  # Use standalone mode instead of Apache plugin
  create_if_missing: true  # Only create certificates if they don't exist
  renew_hook: "systemctl reload apache2"  # Command to run after successful renewal
