# One list entry per virtual host you want on this server.
sites:
  - server_name: zachsexton.com
    root: /var/www/zachsexton.com/html
    aliases:
      - path: /font-helper
        directory: /root/font-helper

  - server_name: petfoodfinder.app
    root: /var/www/petfoodfinder.app/html
