---
- name: restart apache
  systemd:
    name: "{{ apache_service_name | default('apache2') }}"
    state: restarted

- name: reload apache
  systemd:
    name: "{{ apache_service_name | default('apache2') }}"
    state: reloaded