name: Deploy NGINX configuration

on:
  push:
    branches: [ master ]          
  workflow_dispatch:            

jobs:
  configure-nginx:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible python3-jmespath

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add target host key
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 5.161.81.57 >> ~/.ssh/known_hosts
        ssh-keyscan -H web01 >> ~/.ssh/known_hosts   # if alias is used

    - name: Ansible check‑mode (dry run)
      run: |
        ansible-playbook \
          -i ansible/inventory/hosts.ini \
          ansible/personal-web-server/playbooks/site.yml \
          --check --diff

    - name: Apply configuration
      run: |
        ansible-playbook \
          -i ansible/inventory/hosts.ini \
          ansible/personal-web-serverplaybooks/site.yml \
          --diff
