name: Deploy NGINX configuration

on:
  push:
    branches: [ master ]
    paths:
      - 'ansible/**'
  workflow_dispatch:            

jobs:
  configure-nginx:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add target host key
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 5.161.81.57 >> ~/.ssh/known_hosts
